### ISSUE TITLE
Failed to apply profile / Forza Motorsport request

### ISSUE THREAD

**Issue by Gryzzmo** [mistenkt/resize-raccoon#6]
HI,
thank you very much for this brilliant tool! I hoped Forza Motorsport will also work, as it doesn't work with SRWE etc. (only with annoying surround).

Then I try to make a Profile, the Error "Failed to apply profile, not shure why..." comes up. I started both Programs as Admin.

Will there be a integration of Forza, or isn't it possible? I use it via the Xbox App

Thank you :)

**Comment by mistenkt** [comment]
Unfortunately this wont work with games that also aren't supported in SRWE. We both do pretty much the same thing, the only different is how we end up there. (i try to automate more of it so that you shouldn't have to interact with the app much at all after configuring your profiles).  

I did try the new Forza for an hour or so when it came out, but i actually cant remember if i used Nvidia Surround or if i used SRWE (this was before i had started RR). Usually if a game allows you to run in windowed mode or borderless it should work, as long as they actually render the game at the size of the window (some games don't use the window size for the render resolution when in windowed mode, and instead just allow you to select from a list of supported resolutions on your main monitor and other common resolutions and in those cases everything will be stretched and ugly, and nvidia surround is your only solution as this actually makes the games believe there is a single monitor connected that supports that triple screen resolution). 

Unless they release an update that completely changes the physics of this game (it just felt horrible IMO), i probably wont reinstall it and have another look. 

If you want a way to switch between different monitor configurations, one where you run nvidia surround and one without, you should look into [Display Magician](https://github.com/terrymacdonald/DisplayMagician)
